// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkhfefyjsdfvyfelkdxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRraGZlZnlqc2RmdnlmZWxrZHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2OTYxMDMsImV4cCI6MjA1MDI3MjEwM30.BVLeoQITesxGanlKbDVa2ZAbaBFhN79jK2h2FB2OBz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);